### ISSUE TITLE
Within-chain parallelization compilation issues

### ISSUE THREAD

**Issue by rspadial** [paul-buerkner/brms#1182]
I have run into compilation problems using within-chain parallelization when I try to estimate a model that uses the stan function "integrate_1d" . 

Here is simplified example of the model:

```
wtpdata <- read.table(".../wtpdata_test.csv", header=TRUE, sep=",")

stan_funs <- "
  real integrand(real x, real xc, real[] theta, real[] x_r, int[] x_i) {
	  real a = theta[1];
      real p = x_r[1];                	
    return exp(-(-log(x*p))^a);
  }
  real integralfun(data real p, real a, data int xi) {
  	  	return integrate_1d(integrand, 0.0, 1.0, {a}, {p}, {xi}, 0.01);
  }
"

stanvars <- stanvar(scode = stan_funs, block = "functions") 

nlform <- bf(wtp ~ integralfun(prob, a, id), a ~ (1|id), nl = TRUE)

nlprior <- c(prior(lognormal(2, 1), lb=0,  nlpar = "a"))
```

And here is a test dataset: 
[wtpdata_test.csv](https://github.com/paul-buerkner/brms/files/6638832/wtpdata_test.csv)

If I run this code, the sampling goes fine:

`fit2 <- brm(formula = nlform, data = wtpdata, family = zero_one_inflated_beta,
                 prior = nlprior, control = list(adapt_delta = 0.9), stanvars = stanvars, chains = 4, cores = 4, backend = "cmdstanr")`

However, running this one with threading

`fit2 <- brm(formula = nlform, data = wtpdata, family = zero_one_inflated_beta,
                 prior = nlprior, control = list(adapt_delta = 0.9), stanvars = stanvars, chains = 2, cores = 2, threads = threading(2), backend = "cmdstanr")`

leads to compilation error

> Ill-typed arguments supplied to function ‘integralfun’. Available signatures:
(data real, real, data int) => real
Instead supplied arguments of incompatible type: real, real, int.make

 @wds15 found that the problem lies with the declaration of data types in this post: [https://discourse.mc-stan.org/t/non-linear-model-with-integrate-1d-in-bmrs/22941/4?u=rspadial](url)

**Comment by paul-buerkner** [comment]
@wds15 Suppose I would add all data with a `data` identifier, would that work in the new stanc3? And at which version would it work?

**Comment by rok-cesnovar** [comment]
Yes, adding the data qualifier for all data would definitely work, it would also work in stanc2.
Also makes the generated code more optimizible in the future.

**Comment by paul-buerkner** [comment]
So it would also work with rstan 2.19 and 2.21? In that case, I could just add it to `partial_log_lik` unconditionally.

**Comment by paul-buerkner** [comment]
Just realized that those rstan versions don't support threading yet, so it even doesn't matter if the `data` qualifier works for them :-D

**Comment by paul-buerkner** [comment]
Oh well, but it would perhaps be good to also add the data qualifier to other brms-defined Stan functions. So I guess my initial questions: "So it would also work with rstan 2.19 and 2.21?" still stands then.

**Comment by paul-buerkner** [comment]
I added the `data` qualifier to `partial_log_lik` where appropriate so the above brms model should now be working correctly.

**Comment by rok-cesnovar** [comment]
Cant test at the moment as I have the development version of  rstan on the computer I am on right now but `data` qualifiers are present in the documentation for Stan 2.19 so they should work.

**Comment by paul-buerkner** [comment]
Thanks! Are `int` and friends automatically coded as `data` as they can't be parameters?

**Comment by rok-cesnovar** [comment]
Yes, no need to place data with ints.
