### ISSUE TITLE
Error in posterior_predict() under R devel

### ISSUE THREAD

**Issue by strengejacke** [paul-buerkner/brms#1066]
Hi Paul,
for the latest R devel (Windows), I get an error when calling `posterior_predict()`. A reproducible example is here:

``` r
library(brms)
zinb <- read.csv("http://stats.idre.ucla.edu/stat/data/fish.csv")
set.seed(123)
m1 <- brm(bf(
    count ~ persons + child + camper + (1 | persons),
    zi ~ child + camper + (1 | persons)
  ),
  data = zinb,
  family = zero_inflated_poisson(),
  refresh = 0,
  cores = 4
)
posterior_predict(m1)
#> Error in named_list(groups, list()): length(values) == length(names) is not TRUE


> devtools::session_info()
- Session info ------------------------------------------------------------------------------------
 setting  value                                             
 version  R Under development (unstable) (2021-01-08 r79812)
 os       Windows 10 x64                                    
 system   x86_64, mingw32                                   
 ui       RStudio                                           
 language (EN)                                              
 collate  German_Germany.1252                               
 ctype    German_Germany.1252                               
 tz       Europe/Berlin                                     
 date     2021-01-09                                        

- Packages ----------------------------------------------------------------------------------------
 ! package        * version  date       lib source                               
   brms           * 2.14.4   2020-11-03 [1] CRAN (R 4.1.0)  
```

<sup>Created on 2021-01-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by paul-buerkner** [comment]
Thanks for opening this issue! Do you have an idea on what change in R devel has caused this problem? I would prefer not to go down this rabbit hole if there is a high chance this problem won't make it into the released version of 4.1.0

**Comment by strengejacke** [comment]
No, unfortunately not. I only realized this by failing CRAN checks for one of my packages that has been longer on CRAN and suddenly failed. I first thought it was due to updates in other dependent packages, but after finding the source of this error I realized it must be related to (a change in) the R devel version, maybe from the past two weeks.

**Comment by paul-buerkner** [comment]
I see. Can we wait another week, and if the error persists, I will check how to fix it? Or do you need a fix earlier?

**Comment by strengejacke** [comment]
No, there's no pressure. I use `posterior_predict()` to calculate something similar to ICC in mixed models, which is added to a summary table. I wrapped that code in `tryCatch()`, and if `posterior_predict()` fails, the summary table does not contain the ICC (which is not that problematic, especially since it only affects R devel). I sent an update to CRAN, so failing checks should be resolved now, and thus there's no hurry for you to fix this.

**Comment by paul-buerkner** [comment]
Does the error still occur under R-devel at the moment?

**Comment by strengejacke** [comment]
No, now the model won't even compile?

``` r
library(brms)
#> Loading required package: Rcpp
#> Loading 'brms' package (version 2.14.4). Useful instructions
#> can be found by typing help('brms'). A more detailed introduction
#> to the package is available through vignette('brms_overview').
#> 
#> Attaching package: 'brms'
#> The following object is masked from 'package:stats':
#> 
#>     ar
zinb <- read.csv("http://stats.idre.ucla.edu/stat/data/fish.csv")
set.seed(123)
m1 <- brm(bf(
    count ~ persons + child + camper + (1 | persons),
    zi ~ child + camper + (1 | persons)
  ),
  data = zinb,
  family = zero_inflated_poisson(),
  refresh = 0,
  cores = 4
)
#> Compiling Stan program...
#> Error in compileCode(f, code, language = language, verbose = verbose): C:/rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/mail/Documents/R/win-library/4.1/rstan/lib/x64/libStanServices.a(stan_fit.o):stan_fit.cpp:(.data$_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2P1[_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2P1]+0x0): multiple definition of `boost::math::detail::bessel_j0<long double>(long double)::P1'; file21f417ab4415.o:file21f417ab4415.cpp:(.rdata$_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2P1[_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2P1]+0x0): first defined hereC:/rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/mail/Documents/R/win-library/4.1/rstan/lib/x64/libStanServices.a(stan_fit.o):stan_fit.cpp:(.data$_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2QS[_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2QS]+0x0): multiple definition of `boost::math::detail::bessel_j0<long double>(long double)::QS'; file21f417ab4415.o:file21f417ab4415.cpp:(.rdata$_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2QS[_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2QS]+0x0): first defined hereC:/rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/mail/Documents/R/win-library/4.1/rstan/lib/x64/libStanServices.a(stan_fit.o):stan_fit.cpp:(.data$_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2PS[_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2PS]+0x0): multiple definition of `boost::math::detail::bessel_j0<long double>(long double)::PS'; file21f417ab4415.o:file21f417ab4415.cpp:(.rdata$_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2PS[_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2PS]+0x0): first defined hereC:/rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/mail/Documents/R/win-library/4.1/rstan/lib/x64/libStanServices.a(stan_fit.o):stan_fit.cpp:(.data$_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2QC[_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2QC]+0x0): multiple definition of `boost::math::detail::bessel_j0<long double>(long double)::QC'; file21f417ab4415.o:file21f417ab4415.cpp:(.rdata$_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2QC[_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2QC]+0x0): first defined hereC:/rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/mail/Documents/R/win-library/4.1/rstan/lib/x64/libStanServices.a(stan_fit.o):stan_fit.cpp:(.data$_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2PC[_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2PC]+0x0): multiple definition of `boost::math::detail::bessel_j0<long double>(long double)::PC'; file21f417ab4415.o:file21f417ab4415.cpp:(.rdata$_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2PC[_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2PC]+0x0): first defined herecollect2.exe: error: ld returned 1 exit status
#> Error in sink(type = "output"): invalid connection
posterior_predict(m1)
#> Error in posterior_predict(m1): object 'm1' not found

sessionInfo()
#> R Under development (unstable) (2021-01-20 r79850)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 19042)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252   
#> [3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
#> [5] LC_TIME=German_Germany.1252    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] brms_2.14.4 Rcpp_1.0.5 
#> 
#> loaded via a namespace (and not attached):
#>   [1] TH.data_1.0-10       minqa_1.2.4          colorspace_2.0-0    
#>   [4] ellipsis_0.3.1       ggridges_0.5.3       rsconnect_0.8.16    
#>   [7] estimability_1.3     markdown_1.1         base64enc_0.1-3     
#>  [10] rstan_2.21.2         DT_0.17              fansi_0.4.1         
#>  [13] mvtnorm_1.1-1        bridgesampling_1.0-0 codetools_0.2-18    
#>  [16] splines_4.1.0        knitr_1.30           shinythemes_1.1.2   
#>  [19] bayesplot_1.8.0      projpred_2.0.2       jsonlite_1.7.2      
#>  [22] nloptr_1.2.2.2       shiny_1.5.0          compiler_4.1.0      
#>  [25] emmeans_1.5.3        backports_1.2.1      assertthat_0.2.1    
#>  [28] Matrix_1.3-2         fastmap_1.0.1        cli_2.2.0           
#>  [31] later_1.1.0.1        htmltools_0.5.0      prettyunits_1.1.1   
#>  [34] tools_4.1.0          igraph_1.2.6         coda_0.19-4         
#>  [37] gtable_0.3.0         glue_1.4.2           reshape2_1.4.4      
#>  [40] dplyr_1.0.2          V8_3.4.0             vctrs_0.3.6         
#>  [43] nlme_3.1-151         crosstalk_1.1.1      xfun_0.20           
#>  [46] stringr_1.4.0        ps_1.5.0             lme4_1.1-26         
#>  [49] mime_0.9             miniUI_0.1.1.1       lifecycle_0.2.0     
#>  [52] gtools_3.8.2         statmod_1.4.35       MASS_7.3-53         
#>  [55] zoo_1.8-8            scales_1.1.1         colourpicker_1.1.0  
#>  [58] promises_1.1.1       Brobdingnag_1.2-6    parallel_4.1.0      
#>  [61] sandwich_3.0-0       inline_0.3.17        shinystan_2.5.0     
#>  [64] gamm4_0.2-6          yaml_2.2.1           curl_4.3            
#>  [67] gridExtra_2.3        ggplot2_3.3.3        loo_2.4.1           
#>  [70] StanHeaders_2.21.0-7 stringi_1.5.3        highr_0.8           
#>  [73] dygraphs_1.1.1.6     boot_1.3-25          pkgbuild_1.2.0      
#>  [76] rlang_0.4.10         pkgconfig_2.0.3      matrixStats_0.57.0  
#>  [79] evaluate_0.14        lattice_0.20-41      purrr_0.3.4         
#>  [82] rstantools_2.1.1     htmlwidgets_1.5.3    processx_3.4.5      
#>  [85] tidyselect_1.1.0     plyr_1.8.6           magrittr_2.0.1      
#>  [88] R6_2.5.0             generics_0.1.0       multcomp_1.4-15     
#>  [91] pillar_1.4.7         withr_2.3.0          mgcv_1.8-33         
#>  [94] xts_0.12.1           survival_3.2-7       abind_1.4-5         
#>  [97] tibble_3.0.4         crayon_1.3.4         rmarkdown_2.6       
#> [100] grid_4.1.0           callr_3.5.1          threejs_0.3.3       
#> [103] digest_0.6.27        xtable_1.8-4         httpuv_1.5.4        
#> [106] RcppParallel_5.0.2   stats4_4.1.0         munsell_0.5.0       
#> [109] shinyjs_2.0.0
```

<sup>Created on 2021-01-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
This works, but it's an older brms-model-object:

``` r
library(brms)
m <- insight::download_model("brms_zi_2")
posterior_predict(m)
#>         [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
#>    [1,]    0    2    2    0    0    0    0    0    0     0     1     0     0
#>    [2,]    0    0    0    0    0    0    0    0    0     0     0     0     3
#>    [3,]    0    0    1    0    0    1    0    0    0     0     0     0     0
#>  [ reached getOption("max.print") -- omitted 3601 rows ]

m$version
#> $brms
#> [1] '2.13.3'
#> 
#> $rstan
#> [1] '2.21.2'
#> 
#> $stanHeaders
#> [1] '2.21.0.6'
```

<sup>Created on 2021-01-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment]
This is what I get under R 4.0.3:

``` r
library(brms)
zinb <- read.csv("http://stats.idre.ucla.edu/stat/data/fish.csv")
set.seed(123)
m1 <- brm(bf(
    count ~ persons + child + camper + (1 | persons),
    zi ~ child + camper + (1 | persons)
  ),
  data = zinb,
  family = zero_inflated_poisson(),
  refresh = 0,
  cores = 4
)
#> Compiling Stan program...
#> Error in compileCode(f, code, language = language, verbose = verbose): C:/rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/mail/Documents/R/win-library/4.0/rstan/lib/x64/libStanServices.a(stan_fit.o):stan_fit.cpp:(.data$_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2P1[_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2P1]+0x0): multiple definition of `boost::math::detail::bessel_j0<long double>(long double)::P1'; file181049d56f4c.o:file181049d56f4c.cpp:(.rdata$_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2P1[_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2P1]+0x0): first defined hereC:/rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/mail/Documents/R/win-library/4.0/rstan/lib/x64/libStanServices.a(stan_fit.o):stan_fit.cpp:(.data$_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2QS[_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2QS]+0x0): multiple definition of `boost::math::detail::bessel_j0<long double>(long double)::QS'; file181049d56f4c.o:file181049d56f4c.cpp:(.rdata$_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2QS[_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2QS]+0x0): first defined hereC:/rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/mail/Documents/R/win-library/4.0/rstan/lib/x64/libStanServices.a(stan_fit.o):stan_fit.cpp:(.data$_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2PS[_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2PS]+0x0): multiple definition of `boost::math::detail::bessel_j0<long double>(long double)::PS'; file181049d56f4c.o:file181049d56f4c.cpp:(.rdata$_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2PS[_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2PS]+0x0): first defined hereC:/rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/mail/Documents/R/win-library/4.0/rstan/lib/x64/libStanServices.a(stan_fit.o):stan_fit.cpp:(.data$_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2QC[_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2QC]+0x0): multiple definition of `boost::math::detail::bessel_j0<long double>(long double)::QC'; file181049d56f4c.o:file181049d56f4c.cpp:(.rdata$_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2QC[_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2QC]+0x0): first defined hereC:/rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/mail/Documents/R/win-library/4.0/rstan/lib/x64/libStanServices.a(stan_fit.o):stan_fit.cpp:(.data$_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2PC[_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2PC]+0x0): multiple definition of `boost::math::detail::bessel_j0<long double>(long double)::PC'; file181049d56f4c.o:file181049d56f4c.cpp:(.rdata$_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2PC[_ZZN5boost4math6detail9bessel_j0IeEET_S3_E2PC]+0x0): first defined herecollect2.exe: error: ld returned 1 exit status
#> Error in sink(type = "output"): invalid connection

sessionInfo()
#> R version 4.0.3 (2020-10-10)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 19042)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252   
#> [3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
#> [5] LC_TIME=German_Germany.1252    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] brms_2.14.4 Rcpp_1.0.6 
#> 
#> loaded via a namespace (and not attached):
#>   [1] TH.data_1.0-10       minqa_1.2.4          colorspace_2.0-0    
#>   [4] ellipsis_0.3.1       ggridges_0.5.3       rsconnect_0.8.16    
#>   [7] estimability_1.3     markdown_1.1         base64enc_0.1-3     
#>  [10] rstan_2.21.2         DT_0.17              fansi_0.4.2         
#>  [13] mvtnorm_1.1-1        bridgesampling_1.0-0 codetools_0.2-16    
#>  [16] splines_4.0.3        knitr_1.30           shinythemes_1.1.2   
#>  [19] bayesplot_1.8.0      projpred_2.0.2       jsonlite_1.7.2      
#>  [22] nloptr_1.2.2.2       shiny_1.5.0          compiler_4.0.3      
#>  [25] emmeans_1.5.3        backports_1.2.0      assertthat_0.2.1    
#>  [28] Matrix_1.2-18        fastmap_1.0.1        cli_2.2.0           
#>  [31] later_1.1.0.1        htmltools_0.5.1      prettyunits_1.1.1   
#>  [34] tools_4.0.3          igraph_1.2.6         coda_0.19-4         
#>  [37] gtable_0.3.0         glue_1.4.2           reshape2_1.4.4      
#>  [40] dplyr_1.0.3          V8_3.4.0             vctrs_0.3.6         
#>  [43] nlme_3.1-149         crosstalk_1.1.1      xfun_0.20           
#>  [46] stringr_1.4.0        ps_1.5.0             lme4_1.1-26         
#>  [49] mime_0.9             miniUI_0.1.1.1       lifecycle_0.2.0     
#>  [52] gtools_3.8.2         statmod_1.4.35       MASS_7.3-53         
#>  [55] zoo_1.8-8            scales_1.1.1         colourpicker_1.1.0  
#>  [58] promises_1.1.1       Brobdingnag_1.2-6    parallel_4.0.3      
#>  [61] sandwich_3.0-0       inline_0.3.17        shinystan_2.5.0     
#>  [64] gamm4_0.2-6          yaml_2.2.1           curl_4.3            
#>  [67] gridExtra_2.3        ggplot2_3.3.3        loo_2.4.1           
#>  [70] StanHeaders_2.21.0-7 stringi_1.5.3        highr_0.8           
#>  [73] dygraphs_1.1.1.6     boot_1.3-25          pkgbuild_1.2.0      
#>  [76] rlang_0.4.10         pkgconfig_2.0.3      matrixStats_0.57.0  
#>  [79] evaluate_0.14        lattice_0.20-41      purrr_0.3.4         
#>  [82] rstantools_2.1.1     htmlwidgets_1.5.3    processx_3.4.5      
#>  [85] tidyselect_1.1.0     plyr_1.8.6           magrittr_2.0.1      
#>  [88] R6_2.5.0             generics_0.1.0       multcomp_1.4-15     
#>  [91] DBI_1.1.1            pillar_1.4.7         withr_2.4.0         
#>  [94] mgcv_1.8-33          xts_0.12.1           survival_3.2-7      
#>  [97] abind_1.4-5          tibble_3.0.5         crayon_1.3.4        
#> [100] rmarkdown_2.6        grid_4.0.3           callr_3.5.1         
#> [103] threejs_0.3.3        digest_0.6.27        xtable_1.8-4        
#> [106] httpuv_1.5.5         RcppParallel_5.0.2   stats4_4.0.3        
#> [109] munsell_0.5.0        shinyjs_2.0.0
```

<sup>Created on 2021-01-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by paul-buerkner** [comment]
Oh well I cannot fix R problems with Stan from the brms side  :-D

Daniel <notifications@github.com> schrieb am Do., 21. Jan. 2021, 23:31:

**Comment by torkar** [comment]
Can't reproduce this with latest `brms` and `RStudio`, and with `cmdstanr` as a backend. I suggest closing this issue.

**Comment by paul-buerkner** [comment]
Thanks for testing! Did you use the latest R-devel as well?

**Comment by strengejacke** [comment]
I'm not sure why the setup no longer works properly, I haven't re-installed Stan/R for a longer time, and since a few weeks ago, I have these troubles compiling brms-models. Not sure what the source of this error could be. There is a discussion at the Stan forums suggesting it could be related with the setup in makevars.win, however, I removed (renamed) those files, which should at least resolve those problems (I think these were related to Stan and the withr package).

**Comment by torkar** [comment]
Yes I used latest dev. :)

**Comment by strengejacke** [comment]
Just checked the above example on R 4.03, Microsoft R open 4.02 and R dev, and all yielded the same compiling error...

**Comment by paul-buerkner** [comment]
Ok, but the compilation error would then be unrelated to brms. I am closing this issue for now. Thank you both for investigating these problems!

**Comment by strengejacke** [comment]
FYI, I re-installed rstan, re-configured makevars.win / .Renviron files and downgraded to withr 2.2.0... now the initial example works with R 4.0.3 and R devel from 20th Jan.
